version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:5000"  # Mapeia 8000 no host para 5000 no container
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py